import{a as i,i as d}from"./assets/vendor-8cce9181.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();async function l(){const o="https://books-backend.p.goit.global/books/category-list";try{return(await i.get(o)).data}catch(t){console.error("Error fetching books:",t)}}async function u(){try{const o=await l(),t=document.querySelector(".categories-list_books");o.forEach(a=>{const s=document.createElement("li");s.classList.add("item-list_category");const e=document.createElement("a");e.textContent=a.list_name,e.href=`${a.list_name}`,e.classList.add("link_category-book"),s.appendChild(e),t.appendChild(s)})}catch(o){console.error("Error rendering categories:",o)}}document.addEventListener("DOMContentLoaded",u);function n(){localStorage.getItem("theme")==="dark-mode"?(document.querySelector("html").classList.add("dark-mode"),document.querySelector(".switch_input").checked=!0):(document.querySelector("html").classList.remove("dark-mode"),document.querySelector(".switch_input").checked=!1)}window.addEventListener("load",()=>{const o=window.matchMedia("(prefers-color-scheme: dark-mode)"),t=o.matches?"dark-mode":"light";localStorage.theme=localStorage.theme||t,n(),document.querySelector(".switch_input").addEventListener("change",s=>{s.target.checked?(localStorage.setItem("theme","dark-mode"),n()):(localStorage.setItem("theme","light"),n())}),o.addEventListener("change",s=>{const e=s.matches?"dark-mode":"light";localStorage.theme=e,n()})});function m(){d.error({message:"Sorry, there are no books matching your search query. Please try again!",position:"topRight"})}async function h(o){return o.map(({author:t,book_image:a,title:s,description:e,_id:r})=>`<li class="books-item-about" id=${r} >  
    <div class="book-wrap"> 
    <img class="book-img" src="${a}"  alt="${e}"/> 
    </div> 
    <div class="book-info">  
    <p class="info-title">${s}</p>  
    <p class="info-author">${t}</p>  
    </div>  
    </li>`).join("")}async function g(o){return await Promise.all(o.map(async({list_name:t,books:a})=>` 
    <div class="container-books"> 
    <h3 class="book-categoty-title">${t}</h3> 
    <ul class='list-books'>${await h(a)}</ul>  
    <button class="book-button" data-js="${t}">See more</button> 
    </div> 
    `))}async function f(){const o=document.querySelector(".top-categories-list");try{const t=await i.get("https://books-backend.p.goit.global/books/top-books");o.insertAdjacentHTML("afterbegin",'<h2 class="categories-title">Best Sellers<span> Books</span></h2>');const a=await g(t.data);return o.insertAdjacentHTML("beforeend",a),t.data}catch(t){console.log(t.message),m()}}l();document.addEventListener("DOMContentLoaded",n);f();
//# sourceMappingURL=commonHelpers.js.map
